# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: La Patrona Bakery
email: lapatronabakeryhomestead@gmail.com
phone: 305-242-4044
address: "110 W. Mowry Drive Homestead, FL 33030"
description: El Mejor pan Mexicano y Centroamericano del sur de la Florida. Aqui encontraras mas de 100 variedades y la deliciosa Rosca de Reyes!
# baseurl: "/la-patrona-bakery" # the subpath of your site, e.g. /blog
url: "http://www.lapatronabakery.com" # the base hostname & protocol for your site
twitter_username: lapatronabakery
fb_page: LaPatronaBakery
instagram_username: lapatronabakery

# Build settings
markdown: kramdown
permalink: /:title

#Google Maps API
google_api_key: AIzaSyAvR32mUgbr43kCtPMxSMwQxZyCoFgfy48
